name: lint-build-and-tests
on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  linter:
    uses: robergro/spm-poc-common/.github/workflows/linter.yml@main
  buildAndTest:
    uses: robergro/spm-poc-common/.github/workflows/buildAndTest.yml@main