name: build-framework
on:
  pull_request:
    types: [ opened, edited, synchronize ]
    
env:
  spm_name: ${{ vars.SPM_NAME }}-Package
  swift_version: '5.9'
  xcode_path: "/Applications/Xcode_15.0.1.app"
  xcodebuild_sdk: -sdk iphonesimulator
  xcodebuild_destination: -destination 'platform=iOS Simulator,name=iPhone 15 pro'

jobs:
  build:
    name: Build
    runs-on: macos-14
    steps:
    - name: "Package name"
      run: echo "Build ${{ env.spm_name }} SPM"
    - name: Set Swift Version
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ env.swift_version }}
    - name: Get swift version
      run: swift --version
    - name: Select Xcode
      run: sudo xcode-select -s ${{ env.xcode_path }}
    - name: Checkout Action
      uses: actions/checkout@v4
    - name: Build
      run: xcodebuild -scheme ${{ env.spm_name }} ${{ env.xcodebuild_sdk }} ${{ env.xcodebuild_destination }} build

#   test:
#     name: Unit Test and Snapshot Testing
#     needs: [ build ]
#     runs-on: macos-14
#     steps:
#     - name: Set Swift Version
#       uses: swift-actions/setup-swift@v1
#       with:
#         swift-version: '5.9'
#     - name: Get swift version
#       run: swift --version
#     - name: Select Xcode
#       run: sudo xcode-select -s "/Applications/Xcode_15.0.1.app"
#     - name: Checkout Action
#       uses: actions/checkout@v4
#     - name: Run tests
#       run: xcodebuild -scheme SparkTheming-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 pro' test
