name: build-framework
on:
  pull_request:
    types: [ opened, edited, synchronize ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -scheme SparkTheming-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 pro' build
    - name: Run tests
      run: xcodebuild -scheme SparkTheming-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 pro' test
