name: build-framework
on:
  pull_request:
    types: [ opened, edited, synchronize ]
    
jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'
    - name: Get swift version
      run: swift --version
    - name: Select Xcode
      run: sudo xcode-select -s "/Applications/Xcode_15.0.1.app"
    - uses: actions/checkout@v4
    - name: Build
      run: xcodebuild -scheme SparkTheming-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 pro' build
    - name: Run tests
      run: xcodebuild -scheme SparkTheming-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 pro' test
